### PR TITLE
docs(README): use quotes when mentioning `G`

### PR DESCRIPTION
**Pull request by Smugaski**
Letter "G" wasn't in quotes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
wouldnt that make it harder to read

**Comment by Smugaski** [comment]
maybe, but you're not supposed to say "G" cuz it's haram!

**Comment by SuperchupuDev** [comment]
if you manage to somewhat censor it (like with quotes) without making it less readable then sure

**Comment by Smugaski** [comment]
that's what I did lol

**Comment by SuperchupuDev** [comment]
> without making it less readable

**Comment by SuperchupuDev** [comment]
any updates on this???????????'??'??? if you manage to censor the bad letter without using normal quotes while it keeps being readable ill merge it

**Comment by SuperchupuDev** [comment]
hi this pr has been inactive for a while so im closing it

reopen it if you have any updates or something

**Pull request closed without merging**
